const projects = [{
        name: "helloworld",
        title: "Hello World",
        desc: "Project desc",
        bdytxt: "This card was generated by Javascript",
        githubLink: "hello"
    },
    {
        name: "gameon",
        title: "Game On Dude!",
        desc: "frikken sicc man",
        bdytxt: "This was aswell, this is going great",
        githubLink: "game"
    },
    {
        name: "qwerty",
        title: "ASDF",
        desc: "..or you know.. yeah.",
        bdytxt: "Hi guys! I just got added!",
        githubLink: "asdf"
    }
];

function createDOMProjectElements() {
    
    projects.forEach(project => {
        const   newCardDiv = document.createElement('div'),
                newCardTitle = document.createElement('div'),
                newCardDesc = document.createElement('div'),
                newCardBodyText = document.createElement('div'),
                newCardLink = document.createElement('div');

            buildNewCardStructure(newCardDiv, newCardTitle, newCardDesc, newCardBodyText, newCardLink)
            addContentToTitle(project, newCardTitle)
            addContentToDesc(project, newCardDesc)
            addContentToBody(project, newCardBodyText)
            addContentToLink(newCardLink)
            addClasslistToProjectNodes(newCardDiv, newCardTitle, newCardDesc, newCardBodyText, newCardLink, project)
            addLinkToProject(project)
        
        
        
    });
}

function addContentToLink(link) {
    const   linkContent = document.createTextNode('Link to github!'),
            linkNode = document.createElement('a');

    buildIndividualNodesWithContent(link, linkNode, linkContent)
            
}

function addContentToDesc(project, desc) {
    const   descContent = document.createTextNode(project.desc),
            descNode = document.createElement('p');

    buildIndividualNodesWithContent(desc, descNode, descContent)
}

function addContentToTitle(project, title) {
    const   titleContent = document.createTextNode(project.title),
            titleNode = document.createElement('h3');

    buildIndividualNodesWithContent(title, titleNode, titleContent)
}

function buildIndividualNodesWithContent(parent, node, content) {
    node.append(content)
    parent.append(node)
}

function addContentToBody(project, body) {
    const   bodyContent = document.createTextNode(project.bdytxt)
    body.append(bodyContent)
}

function buildNewCardStructure(parent, title, desc, body, link) {
    const   projectContainerDiv = document.querySelector('div.projects_card_container'),
            buildArray = [title, desc, body, link];

    projectContainerDiv.append(parent)
    
    buildArray.forEach(node => {
        parent.append(node)
    });   
}

function addClasslistToProjectNodes(parent, title, desc, body, link, project) {
    parent.classList.add('project_card')
    title.classList.add('project_card_title')
    desc.classList.add('project_card_desc')
    body.classList.add('project_card_bdytxt')
    link.classList.add('project_card_link')
    link.classList.add(project.name)
}

function addLinkToProject(project) {
    const   addLink = document.querySelector('.' + project.name + ' a');
    
    addLink.href = project.githubLink
}